import { useEffect,useState } from 'react';import type { ReportData,Snapshot } from '../types';import { invoke } from '../bridge';import { ReportChart } from '../components/Charts';import { Icon } from '../icons';
const kinds=[['day','日报'],['week','周报'],['month','月报'],['year','年报']];const money=(n:number|null|undefined)=>n==null?'暂无法计算':'¥ '+n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
export function Analysis({state,kind,onKind,onOpenRecords,onCommand}:{state:Snapshot;kind:string;onKind:(kind:string)=>void;onOpenRecords:(ids?:string[])=>void;onCommand:(command:string,payload?:unknown)=>Promise<unknown>}){
 const [report,setReport]=useState<ReportData|null>(null),[table,setTable]=useState(false),[visible,setVisible]=useState({income:true,outflow:true,net:true});useEffect(()=>{invoke<ReportData>('getReport',{kind}).then(setReport)},[kind,state.lastSavedAt,state.hideAllAmounts]);const hidden=state.hideAllAmounts;const metric=(id:string)=>hidden?'••••••':money(report?.metrics[id]);const compare=(id:string)=>{const now=report?.metrics[id],before=report?.comparison[id];if(now==null||before==null)return '无法比较';const delta=now-before;return (delta>=0?'+':'')+delta.toFixed(2)+' 较上一周期'};
 return <div className="page"><div className="page-title"><div><h1>财务分析</h1><p>{report?.periodLabel||'正在生成报告'} · {report?.unit||'人民币元'}</p></div><button className="button ghost" onClick={()=>onCommand('exportReportPdf')}><Icon name="data"/>导出 PDF</button></div><div className="report-tabs" role="tablist">{kinds.map(([id,label])=><button key={id} className={kind===id?'selected':''} onClick={()=>onKind(id)} role="tab" aria-selected={kind===id}>{label}</button>)}</div>
 {report?.dataStatus==='empty'?<section className="panel empty-report"><h2>本周期暂无记录</h2><p>真实的零和没有数据不是一回事。换个周期，或先添加一笔记录。</p></section>:null}
 <div className="analysis-grid report-summary"><section className="panel verdict"><span className="large-icon"><Icon name="shield" size={25}/></span><div><small>自动摘要</small><h2>{report?.summary||state.analysis.verdict}</h2></div></section>{[['inflow','本期流入'],['outflow','本期流出'],['netflow','净现金流']].map(([id,label])=><section className="panel stat" key={id}><small>{label}</small><b>{metric(id)}</b><span>{hidden?'已隐藏':compare(id)}</span></section>)}</div>
 <section className="report-header"><div><h2>现金流变化</h2><p>{report?.generatedAt?`生成于 ${report.generatedAt}`:'加载中'} · 点击数据点查看来源记录</p></div><div className="series-toggles">{(['income','outflow','net'] as const).map(id=><label key={id}><input type="checkbox" checked={visible[id]} onChange={e=>setVisible({...visible,[id]:e.target.checked})}/>{id==='income'?'流入':id==='outflow'?'流出':'净流'}</label>)}</div></section>{report?<ReportChart rows={report.series} hidden={hidden} visible={visible} onPoint={ids=>onOpenRecords(ids)}/>:null}
 <div className="report-kpis">{[['cash','期末现金'],['fixedcost','固定成本'],['variablecost','可变成本'],['payables','应付账款'],['runway','Runway'],['dependency','财务依赖度']].map(([id,label])=><section className="panel stat" key={id}><small>{label}</small><b>{metric(id)}</b><span>{report?.metricStatus[id]==='ready'?'口径可复核':report?.metricStatus[id]||'加载中'}</span></section>)}</div>
 <div className="structure-grid"><Structure title="成本分类 Top 5" rows={report?.costCategories||[]} hidden={hidden} onDrill={onOpenRecords}/><Structure title="收入来源" rows={report?.incomeSources||[]} hidden={hidden} onDrill={onOpenRecords}/></div>
 <section className="panel report-detail"><header><div><h2>报告数据表</h2><p>图表的无障碍替代视图，合计口径与图表一致。</p></div><button className="text-button" onClick={()=>setTable(!table)}>{table?'收起数据表':'查看数据表'}</button></header>{table&&report?<div className="table-wrap"><table><thead><tr><th>周期</th><th className="amount">流入</th><th className="amount">流出</th><th className="amount">净现金流</th><th></th></tr></thead><tbody>{report.series.map(row=><tr key={row.label}><td>{row.label}</td><td className="amount">{hidden?'••••••':money(row.income)}</td><td className="amount">{hidden?'••••••':money(row.outflow)}</td><td className="amount">{hidden?'••••••':money(row.net)}</td><td><button className="text-button" onClick={()=>onOpenRecords(row.recordIds)}>查看记录</button></td></tr>)}</tbody></table></div>:null}</section>
 </div>
}
function Structure({title,rows,hidden,onDrill}:{title:string;rows:{label:string;value:number;recordIds:string[]}[];hidden:boolean;onDrill:(ids?:string[])=>void}){const max=Math.max(1,...rows.map(x=>x.value));return <section className="panel structure-card"><h2>{title}</h2>{rows.length?rows.map(r=><button key={r.label} onClick={()=>onDrill(r.recordIds)}><span>{r.label}</span><i><em style={{width:(r.value/max*100)+'%'}}/></i><b>{hidden?'••••••':money(r.value)}</b></button>):<p className="empty">本周期暂无可分析数据</p>}</section>}