import type { Metric, Snapshot } from '../types'; import { MetricCard } from '../components/MetricCard'; import { Icon } from '../icons';
export function Overview({state,onAdd,onRecord,onPrivacy,onNavigate}:{state:Snapshot;onAdd:()=>void;onRecord:(m:Metric)=>void;onPrivacy:(id:string)=>void;onNavigate:()=>void}){
 const visible=state.metrics.filter(m=>m.isEnabled); const main=visible.slice(0,4), rest=visible.slice(4);
 return <div className="page overview"><div className="page-title"><div><h1>财务总览</h1><p>掌握你的财务现状，专注当下，规划未来。</p></div><button className="button primary" onClick={onAdd}><Icon name="plus"/>新增记录</button></div>
  <div className="metric-grid primary-grid">{main.map(m=><MetricCard key={m.id} metric={m} onRecord={onRecord} onPrivacy={onPrivacy}/>)}</div>
  {rest.length>0&&<div className="metric-grid secondary-grid">{rest.map(m=><MetricCard key={m.id} metric={m} onRecord={onRecord} onPrivacy={onPrivacy}/>)}</div>}
  <section className="panel records-panel"><header><div><h2>最近记录</h2><p>最新的资金变化</p></div><button className="text-button" onClick={onNavigate}>查看全部 <Icon name="chevron" size={16}/></button></header><RecordTable state={state} compact/></section>
 </div>
}
export function RecordTable({state,compact=false,onDelete}:{state:Snapshot;compact?:boolean;onDelete?:(id:string)=>void}){const rows=compact?state.records.slice(0,5):state.records;return <div className="table-wrap"><table><thead><tr><th>日期</th><th>类型</th><th>分类</th><th>账户</th>{!compact&&<th>备注</th>}<th className="amount">金额</th>{onDelete&&<th></th>}</tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.date.slice(0,10)}</td><td><span className={`type-dot ${r.type}`}></span>{r.typeLabel}</td><td>{r.category||'—'}</td><td>{r.account||'—'}</td>{!compact&&<td className="muted">{r.note||'—'}</td>}<td className={`amount ${r.type==='Income'||r.type==='CustomIncrease'?'income':'cost'}`}>{r.displayAmount}</td>{onDelete&&<td><button className="icon-button danger" aria-label="删除记录" onClick={()=>onDelete(r.id)}><Icon name="trash" size={17}/></button></td>}</tr>):<tr><td colSpan={onDelete?7:5}><div className="empty">还没有记录。第一笔从“新增记录”开始。</div></td></tr>}</tbody></table></div>}
