import { useMemo, useState } from 'react';
import type { DashboardLayout, DashboardLayoutItem, Metric,Period,Snapshot } from '../types';import { MetricCard } from '../components/MetricCard';import { MiniTrend } from '../components/Charts';import { Icon } from '../icons';
const periods:[Period,string][]=[['day','今天'],['week','本周'],['month','本月'],['lastMonth','上月'],['year','本年'],['all','全部'],['custom','自定义']];
function item(layout:DashboardLayout|undefined,id:string){return layout?.items.find(candidate=>candidate.widgetId===id)}
export function Overview({state,period,customStart,customEnd,onPeriod,onAdd,onOpenMetric,onRecord,onPrivacy,onNavigate,onReport,onWarnings,onSaveLayout,onResetLayout}:{state:Snapshot;period:Period;customStart:string;customEnd:string;onPeriod:(p:Period,start?:string,end?:string)=>void;onAdd:()=>void;onOpenMetric:(metric:Metric)=>void;onRecord:(metric:Metric)=>void;onPrivacy:(id:string)=>void;onNavigate:()=>void;onReport:()=>void;onWarnings:()=>void;onSaveLayout:(layout:DashboardLayout)=>Promise<void>;onResetLayout:()=>Promise<void>}){
 const [editing,setEditing]=useState(false);const layout=state.dashboardLayout;const visible=state.metrics.filter(metric=>metric.isEnabled);const severityRank:Record<string,number>={关注:1,重要:2,严重:3};const active=(state.warningEvents||[]).filter(event=>event.status==='active'||event.status==='read').sort((a,b)=>severityRank[state.warningRules.find(rule=>rule.id===b.ruleId)?.severity||'关注']-severityRank[state.warningRules.find(rule=>rule.id===a.ruleId)?.severity||'关注']);const highest=active[0],warningRule=highest?state.warningRules.find(rule=>rule.id===highest.ruleId):null;const dates=[...new Set(state.records.map(record=>record.date))].sort().slice(-14);const trend=(dates.length?dates:['—']).map(date=>({label:date==='—'?date:date.slice(5),value:date==='—'?0:state.records.filter(record=>record.date===date).reduce((total,record)=>total+(record.type==='Income'?record.amount:['FixedCost','VariableCost','FixedAssetPurchase','PayablePayment'].includes(record.type)?-record.amount:0),0)}));
 const saveItem=async(widgetId:string,patch:Partial<DashboardLayoutItem>)=>{if(!layout)return;const next={...layout,items:layout.items.map(candidate=>candidate.widgetId===widgetId?{...candidate,...patch}:candidate)};await onSaveLayout(next)};
 const widgetStyle=(widgetId:string)=>{const current=item(layout,widgetId);const isMetric=widgetId.startsWith('metric:');const fallback=isMetric?{w:3,h:2}:{w:widgetId==='cashflow'?5:7,h:4};if(!current)return {gridColumn:`span ${fallback.w}`,gridRow:`span ${fallback.h}`};const minW=Math.max(current.minW||1,isMetric?3:4);const width=Math.min(12,Math.max(minW,current.w||fallback.w));const height=Math.max(current.minH||1,current.h||fallback.h);const x=Math.min(Math.max(0,current.x||0),12-width);return {gridColumn:`${x+1} / span ${width}`,gridRow:`${Math.max(0,current.y||0)+1} / span ${height}`}};
 return <div className="page overview"><div className="page-title"><div><h1>财务总览</h1><p>{state.periodLabel||'全部记录'} · 掌握现状，规划下一步。</p></div><div className="page-title-actions"><button className={'button ghost '+(editing?'primary':'')} onClick={()=>setEditing(current=>!current)}>{editing?'完成布局':'编辑布局'}</button><button className="button primary" onClick={onAdd}><Icon name="plus"/>新增记录</button></div></div><div className="period-selector" role="tablist" aria-label="总览统计周期">{periods.map(([id,label])=><button key={id} role="tab" aria-selected={period===id} className={period===id?'selected':''} onClick={()=>onPeriod(id)}>{label}</button>)}</div>{period==='custom'?<div className="custom-period date-control-grid"><label>开始日期<input type="date" value={customStart} onChange={event=>onPeriod('custom',event.target.value,customEnd)}/></label><label>结束日期<input type="date" value={customEnd} onChange={event=>onPeriod('custom',customStart,event.target.value)}/></label></div>:null}
 {highest&&warningRule?<button className="warning-banner" onClick={onWarnings}><span><Icon name="bell" size={18}/></span><div><b>{warningRule.name}</b><small>{warningRule.severity}级预警已触发 · 前往预警中心查看依据</small></div><Icon name="chevron" size={17}/></button>:null}
 {editing?<div className="layout-editor" role="status"><span>布局编辑已开启。可用键盘按钮调整卡片顺序与大小；窄屏只保留排序。</span><button className="text-button" onClick={()=>onResetLayout()}>恢复默认布局</button></div>:null}
 <div className={'dashboard-grid '+(editing?'is-editing':'')}>{visible.map(metric=>{const widgetId=`metric:${metric.id}`;const current=item(layout,widgetId);return <section className="dashboard-widget" style={widgetStyle(widgetId)} key={widgetId}>{editing?<WidgetControls label={metric.name} item={current} onChange={patch=>saveItem(widgetId,patch)}/>:null}<MetricCard metric={metric} onOpen={onOpenMetric} onRecord={onRecord} onPrivacy={onPrivacy}/></section>})}<section className="dashboard-widget panel overview-chart" style={widgetStyle('cashflow')}>{editing?<WidgetControls label="现金流摘要" item={item(layout,'cashflow')} onChange={patch=>saveItem('cashflow',patch)}/>:null}<header><div><h2>现金流摘要</h2><p>{state.periodLabel||'最近 14 个有记录的日期'}</p></div><button className="text-button" onClick={onReport}>查看完整报告 <Icon name="chevron" size={16}/></button></header><MiniTrend data={trend} hidden={state.hideAllAmounts} title="净现金流趋势"/></section><section className="dashboard-widget panel records-panel" style={widgetStyle('records')}>{editing?<WidgetControls label="最近记录" item={item(layout,'records')} onChange={patch=>saveItem('records',patch)}/>:null}<header><div><h2>最近记录</h2><p>最新的资金变化</p></div><button className="text-button" onClick={onNavigate}>查看全部 <Icon name="chevron" size={16}/></button></header><RecordTable state={state} compact/></section></div></div>
}
function WidgetControls({label,item:onItem,onChange}:{label:string;item?:DashboardLayoutItem;onChange:(patch:Partial<DashboardLayoutItem>)=>void}){const item=onItem;return <div className="widget-controls" aria-label={label+'布局控制'}><span>{label}</span><button type="button" title="上移" aria-label={label+'上移'} onClick={()=>onChange({y:Math.max(0,(item?.y||0)-1)})}>↑</button><button type="button" title="下移" aria-label={label+'下移'} onClick={()=>onChange({y:(item?.y||0)+1})}>↓</button><button type="button" title="减宽" aria-label={label+'减宽'} onClick={()=>onChange({w:Math.max(item?.minW||2,(item?.w||3)-1)})}>−</button><button type="button" title="增宽" aria-label={label+'增宽'} onClick={()=>onChange({w:Math.min(item?.maxW||12,(item?.w||3)+1)})}>＋</button></div>}
export function RecordTable({state,compact=false}:{state:Snapshot;compact?:boolean}){const rows=compact?state.records.slice(0,5):state.records;return <div className="table-wrap"><table><thead><tr><th>日期</th><th>类型</th><th>分类</th><th>资金账户</th>{!compact?<th>备注</th>:null}<th className="amount">金额</th></tr></thead><tbody>{rows.length?rows.map(record=><tr key={record.id}><td>{record.date.slice(0,10)}</td><td><span className={'type-dot '+record.type}></span>{record.typeLabel}</td><td>{record.category||'—'}</td><td>{record.account||'—'}</td>{!compact?<td className="muted">{record.note||'—'}</td>:null}<td className={'amount '+(record.type==='Income'||record.type==='CustomIncrease'?'income':'cost')}>{record.displayAmount}</td></tr>):<tr><td colSpan={6}><div className="empty">还没有记录。第一笔从“新增记录”开始。</div></td></tr>}</tbody></table></div>}
