import { useState } from 'react';
import type { Snapshot } from '../types';
import { Icon } from '../icons';
import { DangerConfirmModal } from '../components/DangerConfirmModal';

export function Settings({state,onCommand,onTheme}:{state:Snapshot;onCommand:(command:string,payload?:unknown)=>Promise<unknown>;onTheme:()=>void}){
 const [diag,setDiag]=useState<{status:string;recoveryMessage?:string;webViewVersion?:string;logEntries:string[]}|null>(null),[danger,setDanger]=useState<'clear'|'factory'|null>(null),[undo,setUndo]=useState<string|null>(null);
 const save=(patch:Record<string,unknown>)=>onCommand('saveSettings',{...state.settings,...patch});
 const execute=async(text:string)=>{const mode=danger!;await onCommand(mode==='clear'?'clearLedger':'factoryReset',{confirmation:text});setUndo(state.lastProtectionSnapshot||'latest');setDanger(null)};
 const bytes=state.dataFileSize||0;const fileSize=bytes<1024?bytes+' B':bytes<1048576?(bytes/1024).toFixed(1)+' KB':(bytes/1048576).toFixed(1)+' MB';
 return <div className="page settings-page"><div className="page-title"><div><h1>设置</h1><p>数据、外观、通知和诊断统一放在这里。</p></div></div>{undo&&<div className="undo-strip"><span>操作完成，保护快照已经创建。</span><button className="text-button" onClick={async()=>{await onCommand('undoLastDanger',undo==='latest'?{}:{path:undo});setUndo(null)}}>撤销并恢复</button></div>}<div className="settings-grid">
  <section className="panel settings-section"><div className="settings-icon"><Icon name="data" size={21}/></div><div><h2>数据与备份</h2><p>数据只保存在本机。迁移电脑时导出备份，在新设备恢复。</p><code>{state.dataFile}</code><div className="data-status-grid"><span>有效记录 <b>{state.recordCount}</b></span><span>回收站 <b>{state.deletedRecordCount}</b></span><span>自定义指标 <b>{state.customMetricCount}</b></span><span>预警规则 <b>{state.warningRuleCount}</b></span><span>文件大小 <b>{fileSize}</b></span><span>完整性 <b>{state.dataIntegrityStatus||'正常'}</b></span><span>数据结构 <b>v{state.schemaVersion}</b></span><span>备份格式 <b>v{state.backupFormatVersion||1}</b></span><span>最近保存 <b>{state.lastSavedAt?new Date(state.lastSavedAt).toLocaleString():'暂无'}</b></span><span>最近备份 <b>{state.lastBackupAt?new Date(state.lastBackupAt).toLocaleString():'暂无'}</b></span></div><div className="button-row"><button className="button primary" onClick={()=>onCommand('backup')}>导出备份</button><button className="button ghost" onClick={()=>onCommand('restore')}>从备份恢复</button><button className="button ghost" onClick={()=>onCommand('openDataFolder')}>打开数据目录</button></div><div className="backup-settings"><label className="setting-toggle"><input type="checkbox" checked={state.settings.autoBackupEnabled} onChange={e=>save({autoBackupEnabled:e.target.checked})}/>启用自动备份</label><label>间隔（天）<input type="number" min="1" max="365" value={state.settings.autoBackupIntervalDays} onChange={e=>save({autoBackupIntervalDays:Number(e.target.value)})}/></label><label>保留份数<input type="number" min="1" max="100" value={state.settings.autoBackupRetentionCount} onChange={e=>save({autoBackupRetentionCount:Number(e.target.value)})}/></label></div><div className="button-row"><button className="button ghost danger-text" onClick={()=>setDanger('clear')}>清空账本</button><button className="button ghost danger-text" onClick={()=>setDanger('factory')}>恢复出厂</button></div></div></section>
  <section className="panel settings-section"><div className="settings-icon"><Icon name="palette" size={21}/></div><div><h2>常规、显示与皮肤</h2><p>选择内置皮肤、CSS 变量皮肤，以及安全垫计算目标。</p><label>安全垫目标<input type="number" min="0" value={state.settings.safetyBufferTarget} onChange={e=>save({safetyBufferTarget:Number(e.target.value)})}/></label><div className="button-row"><button className="button ghost" onClick={onTheme}>打开皮肤设置</button></div></div></section>
  <section className="panel settings-section"><div className="settings-icon"><Icon name="bell" size={21}/></div><div><h2>通知与预警偏好</h2><p>应用内预警始终可用；Windows 通知可单独开关，且默认不显示金额。</p><label className="setting-toggle"><input type="checkbox" checked={state.settings.notificationsEnabled} onChange={e=>save({notificationsEnabled:e.target.checked})}/>允许 Windows 通知</label></div></section>
  <section className="panel settings-section"><div className="settings-icon"><Icon name="shield" size={21}/></div><div><h2>诊断与日志</h2><p>只记录版本、错误类型和操作名，不记录金额、账户、分类或备注。</p><button className="button ghost" onClick={async()=>setDiag(await onCommand('getDiagnostics') as typeof diag)}>检查应用状态</button>{diag&&<div className="diagnostic-result"><b>{diag.status}</b><span>WebView2 {diag.webViewVersion||'未知'} · {diag.logEntries.length?'有 '+diag.logEntries.length+' 条脱敏日志':'暂无需要处理的日志'}</span></div>}</div></section>
  <section className="panel settings-section about-section"><div className="settings-icon"><Icon name="info" size={21}/></div><div><h2>关于 LedgerX</h2><p>本地优先的个人财务指标工具。没有云端，也没有突然出现的会员连续包月。</p><small>v{state.appVersion||'2.1.0'} · MIT License</small></div></section>
 </div>{danger&&<DangerConfirmModal mode={danger} onClose={()=>setDanger(null)} onConfirm={execute}/>}</div>
}