import { useCallback,useEffect,useMemo,useState } from 'react';
import { Sidebar } from './components/Sidebar';import { RecordModal } from './components/RecordModal';import { MetricModal } from './components/MetricModal';import { ThemeModal } from './components/ThemeModal';import { Icon } from './icons';import { invoke } from './bridge';
import type { LedgerRecord,Metric,Page,Period,RecordDraft,Snapshot } from './types';import { Overview } from './pages/Overview';import { Metrics } from './pages/Metrics';import { Records } from './pages/Records';import { Analysis } from './pages/Analysis';import { Settings } from './pages/Settings';import { MetricDetail } from './pages/MetricDetail';import { Warnings } from './pages/Warnings';import { Recovery } from './pages/Recovery';
const themeVars:Record<string,Record<string,string>>={'暖铜':{'--lx-background':'#F7F6F3','--lx-sidebar':'#F1F0ED','--lx-surface':'#FFFDFC','--lx-primary':'#9A6A3A','--lx-primary-hover':'#7D542D','--lx-text':'#1D1D1F','--lx-muted':'#76736F','--lx-border':'#DEDBD5','--lx-selected':'#EDE5DA'},'石墨':{'--lx-background':'#F5F5F4','--lx-sidebar':'#ECECEA','--lx-surface':'#FFFFFF','--lx-primary':'#444443','--lx-primary-hover':'#242424','--lx-text':'#181818','--lx-muted':'#737373','--lx-border':'#DADAD7','--lx-selected':'#DFDFDC'},'深海蓝':{'--lx-background':'#F3F5F7','--lx-sidebar':'#E9EDF1','--lx-surface':'#FCFDFE','--lx-primary':'#294A68','--lx-primary-hover':'#19364F','--lx-text':'#18232D','--lx-muted':'#687681','--lx-border':'#D4DBE1','--lx-selected':'#DCE5EC'}};
function applyTheme(state:Snapshot){const vars=themeVars[state.themeName]||themeVars['暖铜'];Object.entries(vars).forEach(([k,v])=>document.documentElement.style.setProperty(k,v));let style=document.getElementById('custom-theme');if(!style){style=document.createElement('style');style.id='custom-theme';document.head.append(style)}style.textContent=state.customThemeCss||''}
export default function App(){
 const [state,setState]=useState<Snapshot|null>(null),[page,setPage]=useState<Page>('overview'),[recordOpen,setRecordOpen]=useState(false),[preset,setPreset]=useState<Metric|null>(null),[editingRecord,setEditingRecord]=useState<LedgerRecord|null>(null),[metricOpen,setMetricOpen]=useState(false),[themeOpen,setThemeOpen]=useState(false),[selectedMetric,setSelectedMetric]=useState<Metric|null>(null),[metricReturnPage,setMetricReturnPage]=useState<Page>('metrics'),[period,setPeriod]=useState<Period>('all'),[customStart,setCustomStart]=useState(new Date().toISOString().slice(0,7)+'-01'),[customEnd,setCustomEnd]=useState(new Date().toISOString().slice(0,10)),[reportKind,setReportKind]=useState('month'),[recordFilterIds,setRecordFilterIds]=useState<string[]|null>(null),[error,setError]=useState(''),[undoRecordId,setUndoRecordId]=useState<string|null>(null);
 const command=useCallback(async(c:string,p:unknown={})=>{try{const next=await invoke<any>(c,p);if(next&&Array.isArray(next.metrics)){setState(next);applyTheme(next)}return next}catch(e){setError(e instanceof Error?e.message:'操作失败');throw e}},[]);useEffect(()=>{command('getState')},[command]);
 const title=useMemo(()=>({overview:'财务总览',metrics:'指标中心',records:'全部记录',analysis:'财务分析',settings:'设置','metric-detail':'指标详情',warnings:'预警中心'} as Record<Page,string>)[page],[page]);if(!state)return <div className="loading"><span></span><b>LedgerX 正在整理数字</b></div>;if(state.recovery?.required)return <Recovery state={state} onCommand={command}/>;
 const openRecord=(m?:Metric|null)=>{setEditingRecord(null);setPreset(m||null);setRecordOpen(true)};const openEdit=(record:LedgerRecord)=>{setEditingRecord(record);setPreset(null);setRecordOpen(true)};const openMetric=(m:Metric,from:Page='metrics')=>{setSelectedMetric(m);setMetricReturnPage(from);setPage('metric-detail')};const currentMetric=selectedMetric?state.metrics.find(m=>m.id===selectedMetric.id)||selectedMetric:null;
 const changePeriod=async(next:Period,start=customStart,end=customEnd)=>{setPeriod(next);setCustomStart(start);setCustomEnd(end);await command('getDashboard',{period:next,start,end})};const openReport=()=>{setReportKind(period==='day'?'day':period==='week'?'week':period==='year'?'year':'month');setPage('analysis')};
 return <div className="app-shell"><Sidebar page={page} onNavigate={p=>{if(p==='records')setRecordFilterIds(null);setPage(p)}}/><main><div className="mobile-bar"><div className="brand-mini"><img src="./ledgerx-icon.png"/>LedgerX</div><select aria-label="页面" value={page} onChange={e=>setPage(e.target.value as Page)}><option value="overview">财务总览</option><option value="metrics">指标中心</option><option value="records">全部记录</option><option value="analysis">财务分析</option><option value="warnings">预警中心</option><option value="settings">设置</option>{page==='metric-detail'?<option value="metric-detail">指标详情</option>:null}</select></div><div className="top-actions"><span>{title}</span><button className="privacy-button" onClick={()=>command('toggleAllPrivacy')}><Icon name={state.hideAllAmounts?'eyeOff':'eye'} size={18}/>{state.hideAllAmounts?'显示金额':'隐藏金额'}</button></div>
 {page==='overview'?<Overview state={state} period={period} customStart={customStart} customEnd={customEnd} onPeriod={changePeriod} onAdd={()=>openRecord()} onOpenMetric={m=>openMetric(m,'overview')} onRecord={openRecord} onPrivacy={id=>command('toggleMetricPrivacy',{id})} onNavigate={()=>setPage('records')} onReport={openReport} onWarnings={()=>setPage('warnings')}/>:null}
 {page==='metrics'?<Metrics state={state} onAdd={()=>setMetricOpen(true)} onToggle={(id,enabled)=>command('setMetricEnabled',{id,enabled})} onDelete={id=>command('deleteCustomMetric',{id})} onOpen={m=>openMetric(m,'metrics')}/>:null}
 {page==='records'?<Records state={state} focusIds={recordFilterIds} onClearFocus={()=>setRecordFilterIds(null)} onCommand={command} onAdd={()=>openRecord()} onEdit={openEdit} onDelete={async id=>{await command('deleteRecord',{id});setUndoRecordId(id);window.setTimeout(()=>setUndoRecordId(current=>current===id?null:current),8000)}} onRestore={id=>command('restoreRecord',{id})} onPurge={id=>command('purgeRecord',{id})}/>:null}
 {page==='analysis'?<Analysis state={state} kind={reportKind} onKind={setReportKind} onOpenRecords={ids=>{setRecordFilterIds(ids?.length?ids:null);setPage('records')}} onCommand={command}/>:null}
 {page==='settings'?<Settings state={state} onCommand={command} onTheme={()=>setThemeOpen(true)}/>:null}{page==='warnings'?<Warnings state={state} onCommand={command} onOpenRecords={ids=>{setRecordFilterIds(ids);setPage('records')}}/>:null}
 {page==='metric-detail'&&currentMetric?<MetricDetail state={state} metric={currentMetric} period={period} customStart={customStart} customEnd={customEnd} onPeriod={changePeriod} onBack={()=>setPage(metricReturnPage)} onAdd={openRecord} onEdit={openEdit} onPrivacy={id=>command('toggleMetricPrivacy',{id})}/>:null}</main>
 {recordOpen?<RecordModal metrics={state.metrics} preset={preset} record={editingRecord} onClose={()=>{setRecordOpen(false);setEditingRecord(null)}} onSave={(d:RecordDraft)=>command(editingRecord?'updateRecord':'addRecord',editingRecord?{...d,id:editingRecord.id}:d).then(()=>{setRecordOpen(false);setEditingRecord(null)})}/>:null}{metricOpen?<MetricModal onClose={()=>setMetricOpen(false)} onSave={d=>command('addCustomMetric',d).then(()=>setMetricOpen(false))}/>:null}{themeOpen?<ThemeModal state={state} onClose={()=>setThemeOpen(false)} onCommand={command}/>:null}{undoRecordId?<div className="toast action-toast" role="status"><span>记录已移入回收站</span><button onClick={async()=>{await command('restoreRecord',{id:undoRecordId});setUndoRecordId(null)}}>撤销</button></div>:null}{error?<div className="toast" role="alert" onClick={()=>setError('')}>{error}</div>:null}</div>
}