import { useCallback,useEffect,useMemo,useState } from 'react';
import { Sidebar } from './components/Sidebar';import { RecordModal } from './components/RecordModal';import { MetricModal } from './components/MetricModal';import { ThemeModal } from './components/ThemeModal';import { Icon } from './icons';import { invoke, type BridgeCommand } from './bridge';
import type { DashboardLayout, LedgerRecord,Metric,Page,Period,RecordDraft,Snapshot } from './types';import { Overview } from './pages/Overview';import { Metrics } from './pages/Metrics';import { Records } from './pages/Records';import { Analysis } from './pages/Analysis';import { Settings } from './pages/Settings';import { MetricDetail } from './pages/MetricDetail';import { Warnings } from './pages/Warnings';import { Recovery } from './pages/Recovery';
const themeVars:Record<string,Record<string,string>>={'暖铜':{'--lx-background':'#F7F6F3','--lx-sidebar':'#F1F0ED','--lx-surface':'#FFFDFC','--lx-primary':'#9A6A3A','--lx-primary-hover':'#7D542D','--lx-text':'#1D1D1F','--lx-muted':'#76736F','--lx-border':'#DEDBD5','--lx-selected':'#EDE5DA'},'石墨':{'--lx-background':'#F5F5F4','--lx-sidebar':'#ECECEA','--lx-surface':'#FFFFFF','--lx-primary':'#444443','--lx-primary-hover':'#242424','--lx-text':'#181818','--lx-muted':'#737373','--lx-border':'#DADAD7','--lx-selected':'#DFDFDC'},'深海蓝':{'--lx-background':'#F3F5F7','--lx-sidebar':'#E9EDF1','--lx-surface':'#FCFDFE','--lx-primary':'#294A68','--lx-primary-hover':'#19364F','--lx-text':'#18232D','--lx-muted':'#687681','--lx-border':'#D4DBE1','--lx-selected':'#DCE5EC'}};
function applyTheme(state:Snapshot){const vars=themeVars[state.themeName]||themeVars['暖铜'];Object.entries(vars).forEach(([key,value])=>document.documentElement.style.setProperty(key,value));let style=document.getElementById('custom-theme');if(!style){style=document.createElement('style');style.id='custom-theme';document.head.append(style)}style.textContent=state.customThemeCss||''}
export default function App(){
 const [state,setState]=useState<Snapshot|null>(null),[page,setPage]=useState<Page>('overview'),[recordOpen,setRecordOpen]=useState(false),[preset,setPreset]=useState<Metric|null>(null),[editingRecord,setEditingRecord]=useState<LedgerRecord|null>(null),[metricOpen,setMetricOpen]=useState(false),[themeOpen,setThemeOpen]=useState(false),[selectedMetric,setSelectedMetric]=useState<Metric|null>(null),[metricReturnPage,setMetricReturnPage]=useState<Page>('metrics'),[period,setPeriod]=useState<Period>('all'),[customStart,setCustomStart]=useState(new Date().toISOString().slice(0,7)+'-01'),[customEnd,setCustomEnd]=useState(new Date().toISOString().slice(0,10)),[reportKind,setReportKind]=useState('month'),[recordFilterIds,setRecordFilterIds]=useState<string[]|null>(null),[error,setError]=useState(''),[undoRecordId,setUndoRecordId]=useState<string|null>(null);
 const command=useCallback(async(c:string,p:unknown={})=>{try{const next=await invoke(c as BridgeCommand,p as never);if(next&&typeof next==='object'&&Array.isArray((next as Snapshot).metrics)){const snapshot=next as Snapshot;setState(snapshot);applyTheme(snapshot)}return next}catch(error){setError(error instanceof Error?error.message:'操作失败');throw error}},[]);useEffect(()=>{void command('getState')},[command]);
 const title=useMemo(()=>({overview:'财务总览',metrics:'指标中心',records:'全部记录',analysis:'财务分析',settings:'设置','metric-detail':'指标详情',warnings:'预警中心'} as Record<Page,string>)[page],[page]);if(!state)return <div className="loading"><span></span><b>LedgerX 正在整理数字</b></div>;if(state.recovery?.required)return <Recovery state={state} onCommand={command}/>;
 const openRecord=(metric?:Metric|null)=>{setEditingRecord(null);setPreset(metric||null);setRecordOpen(true)};const openEdit=(record:LedgerRecord)=>{setEditingRecord(record);setPreset(null);setRecordOpen(true)};const openMetric=(metric:Metric,from:Page='metrics')=>{setSelectedMetric(metric);setMetricReturnPage(from);setPage('metric-detail')};const currentMetric=selectedMetric?state.metrics.find(metric=>metric.id===selectedMetric.id)||selectedMetric:null;
 const changePeriod=async(next:Period,start=customStart,end=customEnd)=>{setPeriod(next);setCustomStart(start);setCustomEnd(end);await command('getDashboard',{period:next,start,end})};const openReport=()=>{setReportKind(period==='day'?'day':period==='week'?'week':period==='year'?'year':'month');setPage('analysis')};const saveLayout=async(layout:DashboardLayout)=>{await command('saveDashboardLayout',layout)};
 return <div className="app-shell"><Sidebar page={page} profiles={state.profiles} activeProfileId={state.activeProfileId} onSwitchProfile={id=>void command('switchProfile',{id})} onManageProfiles={()=>setPage('settings')} onNavigate={target=>{if(target==='records')setRecordFilterIds(null);setPage(target)}}/><main><div className="mobile-bar"><div className="brand-mini"><img src="./ledgerx-icon.png" alt=""/>LedgerX</div><select aria-label="页面" value={page} onChange={event=>setPage(event.target.value as Page)}><option value="overview">财务总览</option><option value="metrics">指标中心</option><option value="records">全部记录</option><option value="analysis">财务分析</option><option value="warnings">预警中心</option><option value="settings">设置</option>{page==='metric-detail'?<option value="metric-detail">指标详情</option>:null}</select></div><div className="top-actions"><span>{title}</span><button className="privacy-button" onClick={()=>void command('toggleAllPrivacy')}><Icon name={state.hideAllAmounts?'eyeOff':'eye'} size={18}/>{state.hideAllAmounts?'显示金额':'隐藏金额'}</button></div>
 {page==='overview'?<Overview state={state} period={period} customStart={customStart} customEnd={customEnd} onPeriod={changePeriod} onAdd={()=>openRecord()} onOpenMetric={metric=>openMetric(metric,'overview')} onRecord={openRecord} onPrivacy={id=>void command('toggleMetricPrivacy',{id})} onNavigate={()=>setPage('records')} onReport={openReport} onWarnings={()=>setPage('warnings')} onSaveLayout={saveLayout} onResetLayout={async()=>{await command('resetDashboardLayout')}}/>:null}
 {page==='metrics'?<Metrics state={state} onAdd={()=>setMetricOpen(true)} onToggle={(id,enabled)=>void command('setMetricEnabled',{id,enabled})} onCommand={command} onOpen={metric=>openMetric(metric,'metrics')}/>:null}
 {page==='records'?<Records state={state} focusIds={recordFilterIds} onClearFocus={()=>setRecordFilterIds(null)} onCommand={command} onAdd={()=>openRecord()} onEdit={openEdit} onDelete={async id=>{await command('bulkDeleteRecords',{ids:[id]});setUndoRecordId(id);window.setTimeout(()=>setUndoRecordId(current=>current===id?null:current),8000)}} onRestore={id=>void command('bulkRestoreRecords',{ids:[id]})} onPurge={id=>void command('bulkPurgeRecords',{ids:[id]})}/>:null}
 {page==='analysis'?<Analysis state={state} kind={reportKind} onKind={setReportKind} onOpenRecords={ids=>{setRecordFilterIds(ids?.length?ids:null);setPage('records')}} onCommand={command}/>:null}
 {page==='settings'?<Settings state={state} onCommand={command} onTheme={()=>setThemeOpen(true)}/>:null}{page==='warnings'?<Warnings state={state} onCommand={command} onOpenRecords={ids=>{setRecordFilterIds(ids);setPage('records')}}/>:null}
 {page==='metric-detail'&&currentMetric?<MetricDetail state={state} metric={currentMetric} period={period} customStart={customStart} customEnd={customEnd} onPeriod={changePeriod} onBack={()=>setPage(metricReturnPage)} onAdd={openRecord} onEdit={openEdit} onPrivacy={id=>void command('toggleMetricPrivacy',{id})}/>:null}</main>
 {recordOpen?<RecordModal metrics={state.metrics} categories={state.categories||[]} accounts={state.financialAccounts||[]} preset={preset} record={editingRecord} onClose={()=>{setRecordOpen(false);setEditingRecord(null)}} onPreviewDepreciation={payload=>command('previewDepreciation',payload) as Promise<{monthlyAmount?:number;bookValue?:number}>} onSave={(draft:RecordDraft)=>command(editingRecord?'updateRecord':'addRecord',editingRecord?{...draft,id:editingRecord.id}:draft).then(()=>{setRecordOpen(false);setEditingRecord(null)})}/>:null}
 {metricOpen?<MetricModal templates={state.metricTemplates||[]} onClose={()=>setMetricOpen(false)} onAddTemplate={payload=>command('addMetricFromTemplate',payload).then(()=>undefined)} onSaveFormula={async payload=>{const result=await command('saveFormula',payload) as {id?:string};return {id:result.id}}} onSaveMetric={payload=>command('saveMetricDefinition',payload).then(()=>undefined)}/>:null}{themeOpen?<ThemeModal state={state} onClose={()=>setThemeOpen(false)} onCommand={(c,p)=>command(c,p).then(()=>undefined)}/>:null}{undoRecordId?<div className="toast action-toast" role="status"><span>记录已移入回收站</span><button onClick={async()=>{await command('bulkRestoreRecords',{ids:[undoRecordId]});setUndoRecordId(null)}}>撤销</button></div>:null}{error?<div className="toast" role="alert" onClick={()=>setError('')}>{error}</div>:null}</div>
}
