import { useMemo, useState } from 'react';
import type { FormulaToken, MetricTemplate } from '../types';
import { Modal } from './Modal';
import { FormulaBuilder } from './FormulaBuilder';

const blankTokens:FormulaToken[]=[];
export function MetricModal({templates,onClose,onSaveFormula,onAddTemplate,onSaveMetric}:{templates:MetricTemplate[];onClose:()=>void;onSaveFormula:(payload:unknown)=>Promise<{id?:string}>;onAddTemplate:(payload:unknown)=>Promise<void>;onSaveMetric:(payload:unknown)=>Promise<void>}){
 const [group,setGroup]=useState('全部');const [selected,setSelected]=useState<MetricTemplate|null>(null);const [custom,setCustom]=useState(false);const [name,setName]=useState('');const [subtitle,setSubtitle]=useState('');const [displayFormat,setFormat]=useState<'Currency'|'Number'|'Percent'>('Currency');const [tokens,setTokens]=useState<FormulaToken[]>(blankTokens);const [preview,setPreview]=useState('');const [saving,setSaving]=useState(false);
 const groups=useMemo(()=>['全部',...new Set(templates.map(template=>template.group))],[templates]);const visible=templates.filter(template=>group==='全部'||template.group===group);
 const choose=(template:MetricTemplate)=>{setSelected(template);setCustom(false);setName(template.name);setSubtitle(template.description);setFormat(template.displayFormat);setTokens(template.defaultFormula.map(item=>({...item,id:crypto.randomUUID()})));};
 const previewFormula=()=>setPreview(tokens.length?`已组合 ${tokens.map(token=>token.label).join(' ')}；保存时会交给本机公式引擎验证和试算。`:'请至少选择一个数据源。');
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!name.trim())return;setSaving(true);try{if(selected&&!custom){await onAddTemplate({templateId:selected.id,name:name.trim()});}else{const formula=await onSaveFormula({scope:'Metric',tokens,resultType:displayFormat==='Currency'?'Money':displayFormat});await onSaveMetric({name:name.trim(),subtitle:subtitle.trim()||'自定义指标',displayFormat,formulaId:formula.id});}onClose()}finally{setSaving(false)}};
 return <Modal title="新增指标" onClose={onClose} wide><form className="metric-create" onSubmit={submit}><section className="template-library"><header><div><b>先从指标模板开始</b><p>模板提供参考口径，添加后仍可随时修改公式。</p></div><button type="button" className={'button small '+(custom?'primary':'ghost')} onClick={()=>{setCustom(true);setSelected(null);setName('');setSubtitle('');setTokens([])}}>从空白自定义</button></header><div className="template-tabs" role="tablist">{groups.map(item=><button type="button" role="tab" aria-selected={group===item} className={group===item?'selected':''} onClick={()=>setGroup(item)} key={item}>{item}</button>)}</div>{!custom?<div className="template-grid">{visible.map(template=><button type="button" className={selected?.id===template.id?'selected':''} onClick={()=>choose(template)} key={template.id}><b>{template.name}</b><small>{template.description}</small><span>{template.periodBehavior==='PointInTime'?'时点':'期间'} · {template.displayFormat==='Currency'?'金额':template.displayFormat==='Percent'?'百分比':'数值'}</span></button>)}</div>:null}</section>
 <div className="form-grid"><label className="span-2">指标名称<input aria-label="指标名称" value={name} onChange={event=>setName(event.target.value)} placeholder="例如：创作工具成本" autoFocus required/></label><label className="span-2">说明<input aria-label="说明" value={subtitle} onChange={event=>setSubtitle(event.target.value)} placeholder="用于说明指标的口径"/></label><label>显示格式<select value={displayFormat} onChange={event=>setFormat(event.target.value as typeof displayFormat)}><option value="Currency">金额 ¥</option><option value="Number">数值</option><option value="Percent">百分比 %</option></select></label><label>创建方式<select value={custom?'custom':'template'} onChange={event=>setCustom(event.target.value==='custom')}><option value="template" disabled={!selected}>使用模板</option><option value="custom">自定义公式</option></select></label><div className="span-2"><FormulaBuilder scope="Metric" tokens={tokens} onChange={setTokens} onPreview={previewFormula}/>{preview?<p className="formula-preview" role="status">{preview}</p>:null}</div><div className="form-actions span-2"><button type="button" className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={saving||!name.trim()}>{saving?'保存中…':selected&&!custom?'添加模板指标':'保存自定义指标'}</button></div></div>
 </form></Modal>
}
