import { useMemo, useState } from 'react';
import type { CategoryDefinition, DepreciationMethodPayload, FinancialAccount, LedgerRecord, Metric, RecordDraft, SettlementMode } from '../types';
import { Modal } from './Modal';
import { DecimalInput } from './DecimalInput';

const scenes=[['Income','收入'],['VariableCost','日常支出'],['FixedCost','周期成本'],['FixedAssetPurchase','固定资产'],['PayableCreated','应付款'],['CustomIncrease','数值记录']] as const;
const settlementOptions:[SettlementMode,string,string][]=[['PaidFromAccount','从资金账户支付/收款','按结算日期影响所选资金账户'],['IncludedInOpeningBalance','已包含在期初余额','补录历史物品，不重复改变今天的现金'],['CreatePayable','形成应付款','先确认义务，暂不影响现金'],['NoCashImpact','不影响资金','仅记录估值、里程、工时等非资金事实']];
const methods=[['ServicePeriodDaily','服务期逐日分摊'],['PaymentDate','付款日一次性确认'],['CalendarMonth','账单所在自然月'],['PreviousPeriod','上一服务周期'],['CustomFormula','自定义分摊公式']] as const;
const assetMethods=[['StraightLine','直线法'],['UnitsOfProduction','工作量法'],['DoubleDeclining','双倍余额递减法'],['SumOfYears','年数总和法'],['Custom','自定义公式']] as const;
function amount(value:number){return new Intl.NumberFormat('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value)}
export function RecordModal({metrics,categories,accounts,preset,record,onClose,onSave,onPreviewDepreciation}:{metrics:Metric[];categories:CategoryDefinition[];accounts:FinancialAccount[];preset?:Metric|null;record?:LedgerRecord|null;onClose:()=>void;onSave:(draft:RecordDraft)=>Promise<void>;onPreviewDepreciation:(payload:unknown)=>Promise<{monthlyAmount?:number;bookValue?:number}>}){
 const custom=preset?.isCustom?metrics.find(metric=>metric.id===preset.id):record?.customMetricId?metrics.find(metric=>metric.id===record.customMetricId):undefined;
 const initialType=record?.type||(custom?'CustomIncrease':preset?.id==='fixedcost'?'FixedCost':preset?.id==='variablecost'?'VariableCost':preset?.id==='fixedassets'?'FixedAssetPurchase':preset?.id==='payables'?'PayableCreated':'Income');
 const [form,setForm]=useState<RecordDraft>({date:record?.date||new Date().toISOString().slice(0,10),type:initialType,amount:record?.amount||0,category:record?.category||'',account:record?.account||'',note:record?.note||'',customMetricId:record?.customMetricId||custom?.id,metricTargetIds:record?.metricTargetIds||[],incomeSource:record?.incomeSource||undefined,isSelfGeneratedIncome:record?.isSelfGeneratedIncome||false,isNonEssential:record?.isNonEssential||false,categoryId:record?.categoryId||null,settlementMode:record?.settlementMode||'PaidFromAccount',settlementDate:record?.settlementDate||record?.date||new Date().toISOString().slice(0,10),financialAccountId:record?.financialAccountId||accounts.find(account=>!account.isArchived)?.id||null,serviceStart:record?.serviceStart||record?.date||new Date().toISOString().slice(0,10),serviceEndExclusive:record?.serviceEndExclusive||'',billingCadence:record?.billingCadence||'Month',recognitionMethod:record?.recognitionMethod||'ServicePeriodDaily'});
 const [amountText,setAmountText]=useState(form.amount?String(form.amount):'');const [saving,setSaving]=useState(false);const [assetName,setAssetName]=useState('');const [assetLife,setAssetLife]=useState('36');const [residual,setResidual]=useState('0');const [assetMethod,setAssetMethod]=useState<DepreciationMethodPayload>('StraightLine');const [depreciation,setDepreciation]=useState<{monthlyAmount?:number;bookValue?:number}|null>(null);
 const customMetrics=useMemo(()=>metrics.filter(metric=>metric.isCustom&&metric.acceptsDirectRecordAssignment!==false),[metrics]);const needsService=form.type==='FixedCost';const needsAsset=form.type==='FixedAssetPurchase';const affectsCash=form.settlementMode==='PaidFromAccount';const selectedCategory=categories.find(category=>category.id===form.categoryId);
 const set=(patch:Partial<RecordDraft>)=>setForm(current=>({...current,...patch}));
 const toggleMetric=(id:string)=>set({metricTargetIds:(form.metricTargetIds||[]).includes(id)?(form.metricTargetIds||[]).filter(value=>value!==id):[...(form.metricTargetIds||[]),id]});
 const submit=async(event:React.FormEvent)=>{event.preventDefault();const parsed=Number(amountText);if(!Number.isFinite(parsed)||parsed<=0)return;setSaving(true);try{await onSave({...form,amount:parsed,category:selectedCategory?.name||form.category,account:accounts.find(account=>account.id===form.financialAccountId)?.name||form.account,fixedAsset:needsAsset&&assetName.trim()?{name:assetName.trim(),categoryId:form.categoryId||null,acquiredDate:form.date,inServiceDate:form.date,cost:parsed,residualValue:Number(residual||0),usefulLifeMonths:Number(assetLife||0),depreciationMethod:assetMethod}:null});}finally{setSaving(false)}};
 const previewAsset=async()=>setDepreciation(await onPreviewDepreciation({cost:Number(amountText||0),residualValue:Number(residual||0),usefulLifeMonths:Number(assetLife||0),depreciationMethod:assetMethod}));
 return <Modal title={record?'编辑记录':custom?`记录 · ${custom.name}`:'新增记录'} onClose={onClose} wide><form onSubmit={submit} className="form-grid record-form">
  <fieldset className="span-2 scene-picker"><legend>记录场景</legend>{scenes.map(([value,label])=><label key={value}><input type="radio" name="scene" checked={form.type===value||((form.type==='CustomDecrease')&&value==='CustomIncrease')} onChange={()=>set({type:value,settlementMode:value==='CustomIncrease'?'NoCashImpact':form.settlementMode})}/><span>{label}</span></label>)}</fieldset>
  <label>发生日期<input type="date" value={form.date} onChange={event=>set({date:event.target.value})} required/></label>
  <label>金额 / 数值<DecimalInput label="金额 / 数值" autoFocus value={amountText} onChange={setAmountText} required/></label>
  <label className="span-2">分类<select aria-label="分类" value={form.categoryId||''} onChange={event=>{const category=categories.find(item=>item.id===event.target.value);set({categoryId:event.target.value||null,category:category?.name||''})}} required><option value="">选择分类</option>{categories.filter(category=>!category.isArchived).map(category=><option key={category.id} value={category.id}>{category.parentId?`${category.parentId} · `:''}{category.name}</option>)}</select><small>分类说明“这是什么”；归集指标说明“希望如何计算”。</small></label>
  <fieldset className="span-2 assignment-picker"><legend>归集指标（可选）</legend>{customMetrics.length?customMetrics.map(metric=><label key={metric.id}><input type="checkbox" checked={(form.metricTargetIds||[]).includes(metric.id)} onChange={()=>toggleMetric(metric.id)}/><span>{metric.name}</span></label>):<p>创建可直接归集的自定义指标后，会显示在这里。</p>}</fieldset>
  <fieldset className="span-2 settlement-picker"><legend>结算方式</legend>{settlementOptions.map(([value,label,description])=><label key={value}><input type="radio" name="settlement" checked={form.settlementMode===value} onChange={()=>set({settlementMode:value})}/><span><b>{label}</b><small>{description}</small></span></label>)}</fieldset>
  {affectsCash?<><label>资金账户<select aria-label="资金账户" value={form.financialAccountId||''} onChange={event=>set({financialAccountId:event.target.value||null})} required><option value="">选择资金账户</option>{accounts.filter(account=>!account.isArchived).map(account=><option key={account.id} value={account.id}>{account.name} · {account.balanceSide==='Asset'?'资产':'负债'}</option>)}</select></label><label>结算日期<input type="date" value={form.settlementDate||form.date} onChange={event=>set({settlementDate:event.target.value})}/></label></>:null}
  {needsService?<><fieldset className="span-2 service-fields"><legend>服务期间与分摊</legend><label>计费单位<select value={form.billingCadence} onChange={event=>set({billingCadence:event.target.value as RecordDraft['billingCadence']})}><option value="Day">按日</option><option value="Week">按周</option><option value="Month">按月</option><option value="Year">按年</option><option value="Custom">自定义</option><option value="Once">一次性</option></select></label><label>确认方式<select value={form.recognitionMethod} onChange={event=>set({recognitionMethod:event.target.value as RecordDraft['recognitionMethod']})}>{methods.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>服务开始<input type="date" value={form.serviceStart||''} onChange={event=>set({serviceStart:event.target.value})}/></label><label>服务结束（不含当日）<input type="date" value={form.serviceEndExclusive||''} onChange={event=>set({serviceEndExclusive:event.target.value})}/></label><p className="span-2 formula-hint">默认按实际服务期间逐日确认。付款日只影响现金流，服务期间决定日、周、月、年成本；非月初订阅不会被硬塞进某一个自然月。</p></fieldset></>:null}
  {needsAsset?<fieldset className="span-2 asset-fields"><legend>固定资产与折旧</legend><label>资产名称<input value={assetName} onChange={event=>setAssetName(event.target.value)} placeholder="例如：工作电脑"/></label><label>预计使用寿命（月）<DecimalInput label="预计使用寿命（月）" value={assetLife} onChange={setAssetLife}/></label><label>预计残值<DecimalInput label="预计残值" value={residual} onChange={setResidual}/></label><label>折旧方法<select value={assetMethod} onChange={event=>setAssetMethod(event.target.value as DepreciationMethodPayload)}>{assetMethods.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button type="button" className="button ghost" onClick={previewAsset}>预览折旧</button>{depreciation?<p className="formula-hint">预计每月折旧 ¥ {amount(depreciation.monthlyAmount||0)}，初始账面价值 ¥ {amount(depreciation.bookValue||0)}。正式结果由本机引擎确认。</p>:null}</fieldset>:null}
  {record?<div className="edit-preview span-2" role="status"><b>修改预览</b><span>{record.typeLabel} ¥ {amount(record.amount)} → {scenes.find(([value])=>value===form.type)?.[1]||'记录'} ¥ {amount(Number(amountText||0))}</span><small>保存后将由本机引擎重新计算现金、服务期间成本、资产和指标。</small></div>:null}
  <label className="span-2">备注<textarea value={form.note} onChange={event=>set({note:event.target.value})} placeholder="可选"/></label><div className="form-actions span-2"><button type="button" className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={saving}>{saving?'保存中…':record?'保存修改':'保存记录'}</button></div>
 </form></Modal>
}
